CREATE TABLE [dbo].[Employee]
(
	[EmployeeId] bigint NOT NULL PRIMARY KEY identity(1,1) ,
	[EmployeeCode] varchar(10) not null UNIQUE,
	[FirstName] varchar(max) null,
	[LastName] varchar(max) null,
	[FatherName] varchar(max) null,
	[MotherName] varchar(max) null,
	[Gender] varchar(max) null,
	[DateOfBirth] datetimeoffset null,
	[Email] varchar(max) null,
	[Phone] varchar(max) null,
	[UserId] bigint null,
	[RoleId] bigint null,
	[DepartmentId] bigint null,
	[DesignationId] bigint null,
	[StartedOn] datetimeoffset null,
	[EndedOn] datetimeoffset null,
	[ResignedOn] datetimeoffset null,
	[LastWorkingDay] datetimeoffset null,
	[OfferRelesedOn] datetimeoffset null,
	[OfferAcceptedOn] datetimeoffset null,
	[OfferPrice] decimal(22,11) null ,
	[CurrentPrice] decimal(22,11) null ,
	[JoiningBonus] decimal(22,11) null ,
	[CreatedBy] bigint null,
	[CreatedOn] datetimeoffset null,
	[ModifiedBy] bigint null,
	[ModifiedOn] datetimeoffset null,
	[IsActive] bit  null,
	FOREIGN KEY (RoleId) REFERENCES Roles(Id),
	FOREIGN KEY (DepartmentId) REFERENCES Department(DepartmentId),
	FOREIGN KEY (DesignationId) REFERENCES Designation(DesignationId),
)
