CREATE TABLE [dbo].[EmployeeSalaryStructure]
(
	[EmployeeSalaryStructureId] bigint NOT NULL PRIMARY KEY identity(1,1),
	[EmployeeId] bigint null,
	[PAN] varchar(max) null,
	[Adhar] varchar(max) null,
	[BankAccount] varchar(max) null,
	[BankName] varchar(max) null,
	[IFSC] varchar(max) null,
	[BASIC] decimal(10,2) NULL,
	[HRA] decimal(10,2) NULL,
	[CONVEYANCE]  decimal(10,2) NULL,
	[MEDICALALLOWANCE] decimal(10,2) NULL,
	[SPECIALALLOWANCE] decimal(10,2) NULL,
	[SPECIALBONUS] decimal(10,2) NULL,
	[STATUTORYBONUS] decimal(10,2) NULL,
	[OTHERS] decimal(10,2) NULL,
	[PF] decimal(10,2) NULL,
	[ESIC] decimal(10,2) NULL,
	[PROFESSIONALTAX] decimal(10,2) NULL,
	[GroupHealthInsurance] decimal(10,2) NULL,
	[GROSSEARNINGS] decimal(10,2) NULL,
	[GROSSDEDUCTIONS] decimal(10,2) NULL,
	[CreatedBy]   Bigint   NULL,
    [CreatedOn]   DATETIMEOFFSET (7) NULL,
	[ModifiedBy]  Bigint NULL,
	[ModifiedOn]  DATETIMEOFFSET NULL,
    [IsActive]    BIT   NULL,
	FOREIGN KEY (EmployeeId) REFERENCES Employee(EmployeeId)
)
